<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sql_debug"
 *
 * Auto generated by Extension Builder 2015-01-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Debug example',
	'description' => 'Debugging extbase queries in TYPO3 8.7 with Doctrine DBAL',
	'category' => 'plugin',
	'author' => 'Kevin Ditscheid',
	'author_email' => 'kevinditscheid@gmail.com',
	'state' => 'experimental',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '8.7',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);